const content = [
  "\"Too gay to function\"!?",
  "120 calories and 48 calories from fat. What percent is that?",
  "Alyssa, I'm sorry I called you a gap-toothed bitch. It's not your fault you're so gap-toothed.",
  "An \"ex-wife.\"",
  "And even in fancy countries like the United States and England, seven out of ten girls have a negative body image.",
  "And evil takes a human form in Regina George. Don't be fooled because she may seem like your typical selfish, back-stabbing slut faced ho-bag, but in reality, she's so much more than that.",
  "And he told her she was pretty.",
  "And I want my pink shirt back! I want my pink shirt back!",
  "And if any freshmen tried to disturb that peace, well, let's just say we knew how to take care of it.",
  "And I'm sorry for repeating it now.",
  "And I'm sorry for telling everyone about it.",
  "And none for Gretchen Wieners, bye.",
  "And on the third day, God created the Remington bolt-action rifle, so that Man could fight the dinosaurs. And the homosexuals.",
  "And you are... a zombie bride.",
  "And you can only wear your hair in a ponytail once a week, so I guess you chose today.",
  "Ashton Kutcher.",
  "At least you guys can wear halters. I've got man shoulders.",
  "At your age, you're going to have a lot of urges. You're going to want to take off your clothes, and touch each other. But if you do touch each other, you *will* get chlamydia... and die.",
  "Because it's the same in every country.",
  "Because that vest was disgusting!",
  "Boo, you whore.",
  "But if you like him, whatever. I mean I could talk to him for you if you want.",
  "But I'm always on your left!",
  "But the whole dance will be backwards! I'm always on your left!",
  "But you do have to watch out for \"frenemies.\"",
  "Cady, do you even know who sings this?",
  "Cady, this is your night. Don't let the hataz stop you from doin' ya thang!",
  "Calling somebody else fat won't make you any skinnier. Calling someone stupid doesn't make you any smarter. And ruining Regina George's life definitely didn't make me any happier. All you can do in life is try to solve the problem in front of you.",
  "Can I get you guys anything? Some snacks? A condom? Let me know!",
  "Can I help you?",
  "Can you believe my f-ing mom is here?",
  "Cause she's a life ruiner. She ruins people's lives.",
  "Coach Carr, step away from the underage girls!",
  "Cold, Shiny, Hard, PLASTIC.",
  "Come on! We could publish it and then everybody would see what an ax-wound she really is!",
  "Crack.",
  "Damn, Africa, what happened?",
  "Did you have an awesome time? Did you drink awesome shooters, listen to awesome music, and then just sit around and soak up each others awesomeness?",
  "Did you just say \"thang\"?",
  "Did you see nipple? It only counts if you saw a nipple!",
  "Did your teacher ever try to sell you marijuana or ecstasy tablets?",
  "Do you know what people say about you? They say you are homeschooled jungle freak who's a less hot version of me. So don't try to act all innocent. You can take that fake apology and shove it straight up your hairy little...",
  "Do you remember your phone number? I wrote it down for you just in case. Put it in your pocket, I don't want you to lose it. OK? You ready?",
  "Do you wanna do something fun? Wanna go to taco bell?",
  "Don't be. You can do this. There's nothing to break your focus, because not one of those Marymount boys is cute.",
  "Don't have sex, because you will get pregnant -- and die! Don't have sex in the missionary position, don't have sex standing up, just don't do it, OK, promise? OK, now everybody take some rubbers.",
  "Everyone in Africa knows Swedish",
  "Explain how you forgot to invite us to your party?",
  "Fat whore!",
  "Fine! You can walk home, bitches.",
  "Frenemies are enemies who act like friends. We call them \"frenemies\".",
  "Get in loser, we're going shopping.",
  "Glenn Coco? FOUR for you, Glenn Coco! You go, Glenn Coco.",
  "God! See, at least me and Regina George know we're mean! You try to act so innocent like, \"Oh, I use to live in Africa with all the little birdies, and the little monkeys!\"",
  "God. My hips are huge!",
  "Good news, they didn't get run over... Bad news, they're still flat.",
  "Good. So it's settled. So you can go shave your back now. Bye, Jason.",
  "Gretchen Wieners had cracked.",
  "Gretchen, stop trying to make fetch happen! It's not going to happen!",
  "Grool... I meant to say cool and then I started to say great.",
  "Growing up female in this world is not easy. In China, baby girls are routinely put up for adoption. And in parts of Africa, women are still made to live in tents during the time of their menses.",
  "Half the people in this room are mad at me, and the other half only like me because they think I pushed somebody in front a bus, so that's not good.",
  "Happy holidays everybody!",
  "Hell, no. I did *not* leave the South Side for this!",
  "Her favorite movie is Varsity Blues.",
  "Her name is Cady. Cady Heron. Where are you, Cady?",
  "Hey, Africa.",
  "Hey, buddy, you're not pretending anymore. You're plastic. Cold, shiny, hard plastic.",
  "Hey, that's only ok when I say it.",
  "Hey, you guys! Happy hour is from four to six!",
  "Hi, I don't know if anyone told you about me, I'm a new student here, my name is Cady Heron.",
  "I can stick my whole fist in my mouth! Wanna see?",
  "I can't believe you think I like attention!",
  "I can't go out tonight. *cough cough* I'm sick.",
  "I can't go to Taco Bell, I'm on an all-carb diet. GOD Karen you're so stupid!",
  "I care. Every year the seniors through this dance for the underclassmen called the Spring Fling. And whosoever is elected King and Queen automatically become head of the Student Activities Committee and since I am an active member of the Student Activities Committee, I would safely say, I care.",
  "I didn't want anyone else to have it. But that's just me.",
  "I don't hate you because you're fat. You're fat because I hate you.",
  "I don't know, I mean, she's so weird, she just, you know, came up to me and started talking to me about crack.",
  "I don't know, now that she's getting fatter she's got pretty big jugs.",
  "I don't send them, I just get them. So you better send me one, byotch.",
  "I don't think my father, the inventor of Toaster Strudel, would be too pleased with this.",
  "I gave him everything... I was half a virgin when I met him!",
  "I have really bad breath in the morning.",
  "I have this theory, that if you cut off all her hair she'd look like a British man.",
  "I hear her hair's insured for $10,000.",
  "I hear Regina George is dating Aaron Samuels again. The 2 were seen canoodling at Chris Isen's halloween party... they've been inseparable ever since.",
  "I hear she does car commercials... in Japan.",
  "I just wanted to say that you're all winners. And that I couldn't be happier the school year is ending.",
  "I know having a boyfriend might seem like the only thing important to you right now, but you don't have to dumb yourself down in order for a guy to like you.",
  "I know it may look like I was being like a bitch, but that's only because I was acting like a bitch.",
  "I know, right?",
  "I love her. She's like a Martian!",
  "I mean no offense, but why would she send you a candy cane? She doesn't even like you that much. Maybe she feels weird around me because I'm the only person who knows about her nose job. Oh my god, pretend you didn't hear that.",
  "I really wanna lose three pounds.",
  "I saw Cady Heron wearing army pants and flip flops, so I bought army pants and flip flops.",
  "I used to think there was just fat and skinny. But apparently there's lots of things that can be wrong on your body.",
  "I will keep you here until four.",
  "I wish we could all get along like we used to in middle school... I wish I could bake a cake filled with rainbows and smiles and everyone would eat and be happy...",
  "I'd rather see you out there shakin' that thang.",
  "If only you knew how mean she really is... You'd know that I'm not allowed to wear hoop earrings, right? Yeah! Two years ago she told me hoops earrings were *her* thing and I wasn't allowed to wear them anymore. And then for Hannakuh my parents got this pair of really expensive white gold hoops and I had to pretend like I didn't even like them and... it was so sad. And you know she cheats on Aaron? Yes, every Thursday he thinks she's doing SAT prep but really she's hooking up with Shane Oman in the projection room above the auditorium! I never told anybody that because I am *such* a good friend!",
  "If you're from Africa, why are you white?",
  "I'm a MOUSE. DUH.",
  "I'm from Michigan!",
  "I'm new. I just moved here from Africa.",
  "I'm not a regular mom, I'm a cool mom.",
  "I'm sorry that people are so jealous of me... but I can't help it that I'm popular.",
  "In Girl World, Halloween is the one night a year when a girl can dress like a total slut and no other girls can say anything about it",
  "In the real world, Halloween is when kids dress up in costumes and beg for candy.",
  "Irregardless, ex-boyfriends are just off limits to friends. I mean that's just like the rules of feminism.",
  "Is butter a carb?",
  "Is that a band?",
  "Is your muffin buttered?",
  "It's 40 percent. Well 48 over 120 equals X over 100 and then you cross multiply and get the value of X.",
  "It's called the South Beach Fat Flush and all you drink is cranberry juice for 72 hours.",
  "It's Halloween.",
  "It's like I have ESPN or something. My breasts can always tell when it's going to rain.",
  "It's not my fault you're like, in love with me, or something!",
  "Janis Ian - Dyke.",
  "Janis, I cannot stop this car. I have a curfew.",
  "Jason, you do not come to a party at my house with Gretchen and then scam on some poor innocent girl right in front of us three days later. She's not interested. Do you want to have sex with him?",
  "Joking. Sometimes older people make jokes.",
  "Just kidding.",
  "K.G. and the power of 3!",
  "Look, I don't mean to hurt your feelings, but I only date women of color.",
  "Ma'am, do you have this in the next size up?",
  "Made out with a hot dog? Oh my God that was one time!",
  "Make sure you check out her mom's boob job. They're hard as rocks.",
  "Miss Smith, why would Regina refer to herself as a \"fugly slut\"?",
  "Motherf -",
  "My apologies. I have a nephew named Anfernee, and I know how mad he gets when I call him Anthony. Almost as mad as I get when I think about the fact that my sister named him Anfernee.",
  "My nana takes her wig off when she is drunk.",
  "Never in my 14 years as an educator have I seen such behavior. And from young ladies. I've got parents calling me on the phone and asking, \"Did someone get shot?\"",
  "Nice wig, Janis. What's it made of?",
  "No! Do you know what everyone says about you behind your back? Hmm? They say that you're a homeschooled jungle freak, that's a less hot version of me! Yeah, so don't try to act so innocent! You can take that fake apology, and shove it right up your hairy c...",
  "No, I know what home-school is, I'm not retarded!",
  "No... I just have a lot of feelings...",
  "Oh god, busted! Just start apologizing and crying. No, play it cool.",
  "Oh my God - Danny DeVito! I love your work!",
  "Oh my God, Karen, you can't just ask people why they're white.",
  "Oh my god, she's so annoying.",
  "Oh no, I can't say anything else until I have a parent or lawyer present.",
  "Oh no, trust me, I know exactly how to play it. But wait, aren't you *so* mad at Gretchen for telling me? Because if you are you can tell me, it was a really bitchy thing for her to do.",
  "Oh please. I hate my calves.",
  "Oh, God, honey, no! What kind of mother do you think I am? Why, do you want a little bit? Because if you're going to drink I'd rather you do it in the house.",
  "Oh, hi. Did you wanna buy some drugs?",
  "Oh, I love seeing teachers outside of school. It's like seeing a dog walk on its hind legs.",
  "Oh, no. It was coming up again, word vomit... no, wait a minute… Actual vomit.",
  "Oh, Regina gave me some perfume.",
  "Oh, that's original.",
  "Oh, you'll get socialized all right, a little slice like you.",
  "Oh. My carpal tunnel came back.",
  "Ok, so we're all here 'cause of this book, right? Well, I don't know who wrote this book, but you all have got to stop calling each other sluts and whores. It just makes it ok for guys to call you sluts and whores.",
  "Okay, I'm going to forgive you because I'm a very Zen person... and I'm on a lot of pain medication right now.",
  "Okay, yeah. I've got an apology. So, I have this friend who is a new student this year. And I convinced her that it would be fun to mess up Regina George's life. So I had her pretend to be friends with Regina, and then she would come to my house after and we would just laugh about all the dumb stuff Regina said. And we gave these candy bar things that would make her gain weight, and then we turned her best friends against her. And then... Oh yeah, Cady - you know my friend Cady? She made out with her boyfriend, and we convinced him to break up with her. Oh, God, and we gave her foot cream instead of face wash. God! I am so sorry Regina. Really, I don't know why I did this. I guess it's probably because I've got a big lesbian crush on you! Suck on that!",
  "On Wednesdays we wear pink!",
  "One time she met John Stamos on a plane...",
  "One time she punched me in the face... it was awesome.",
  "Own it.",
  "Please stop talking.",
  "Raise your hand if you have ever been personally victimized by Regina George.",
  "Regina George is flawless.",
  "Regina George is not sweet! She's a scum-sucking road whore, she ruined my life!",
  "Regina George... How do I begin to explain Regina George?",
  "Regina said she'll talk to Aaron. And now she is. How can Janis hate her? She's such a good... SLUT!",
  "Regina, you're wearing sweatpants. It's Monday.",
  "Right. Oh, and it's the same with guys. Like, you may think you like someone, but you could be wrong.",
  "Same with Gretchen. The meaner Regina was to her, the more Gretchen tried to win Regina back. She knew it was better to be in the plastics, hating life, than to not be in at all. Because being with the plastics was like being famous... people looked at you all the time and everybody just knew stuff about you.",
  "Say crack again.",
  "See? That's the thing with you plastics. You think everybody is in love with you when actually, everybody HATES you! Like, Aaron Samuels, for example, he broke up with Regina and guess what? He still doesn't want you! So why are you still messing with Regina, Cady? I'll tell you why, because you are a mean girl! You're a bitch! Here. You can have this. It won a prize.",
  "She always looks fierce. She always wins Spring Fling Queen.",
  "She asked me how to spell orange.",
  "She doesn't even go here!",
  "She thinks she's gonna have a party and not invite me? Who does she think she is?",
  "She's fabulous, but she's evil.",
  "She's not even that good looking if you really look at her.",
  "She's so pathetic. Let me tell you something about Janis Ian. We were best friends in middle school. I know, right? It's so embarrassing. I don't even... Whatever. So then in eighth grade, I started going out with my first boyfriend Kyle who was totally gorgeous but then he moved to Indiana, and Janis was like, weirdly jealous of him. Like, if I would blow her off to hang out with Kyle, she'd be like, \"Why didn't you call me back?\" And I'd be like, \"Why are you so obsessed with me?\" So then, for my birthday party, which was an all-girls pool party, I was like, \"Janis, I can't invite you, because I think you're lesbian.\" I mean I couldn't have a lesbian at my party. There were gonna be girls there in their *bathing suits*. I mean, right? She was a LESBIAN. So then her mom called my mom and started yelling at her, it was so retarded. And then she dropped out of school because no one would talk to her, and she came back in the fall for high school, all of her hair was cut off and she was totally weird, and now I guess she's on crack.",
  "She's the queen bee - the star, those other two are just her little workers.",
  "She's totally rich because her dad invented Toaster Strudel.",
  "Shut up.",
  "So that's against the rules, and you can't sit with us.",
  "So you agree? You think you're really pretty?",
  "So, you have your cousins, and then you have your first cousins, and then you have your second cousins...",
  "Somebody wrote in that book that I'm lying about being a virgin because I use super jumbo tampons... but I can't help it if I've got a heavy flow and a wide set vagina!",
  "Sorry, we only carry sizes 1, 3, and 5. You could try Sears.",
  "Still half-true.",
  "Still true.",
  "Stop making this about you. I'm the one that got hit by the bus.",
  "Talk to me again and I'll kick your ass!",
  "That Cady girl is hot... she might even be hotter than Regina George.",
  "That is the ugliest f-ing skirt I've ever seen.",
  "That knew girl moved here from Africa.",
  "That little one, that's Gretchen Wieners.",
  "That one there, that's Karen Smith. She is one of the dumbest girls you will ever meet. Damien sat next to her in English last year.",
  "That's funny, put that in there.",
  "That's me. It's pronounced like Katie.",
  "That's not right, is it?",
  "That's only okay when I say it!",
  "That's why her hair is so big, it's full of secrets.",
  "The limit does not exist!",
  "The weird thing about hanging out with Regina was that I could hate her, and at the same time, I still wanted her to like me.",
  "There are two kinds of evil people in this world. Those who do evil stuff and those who see evil stuff being done and don't try to stop it.",
  "There's a 30% chance that it's already raining!",
  "They were real that day I wore a vest!",
  "This is your lunch, OK? I put a dollar in there so you can buy some milk; you can ask one of the big kids where to do that.",
  "This isn't even cranberry juice, it's cranberry juice cocktail. It's all sugar.",
  "Those bitches.",
  "To find out that everyone hates me? I don't care!",
  "Trang Pak made out with Coach Carr! And so did Sun Jin Dinh!",
  "Um, is there alcohol in this?",
  "Um... the Spice Girls?",
  "Vintage, so adorable.",
  "Watch out please! Fresh meat coming through!",
  "We gotta crack Gretchen Wieners. We crack Gretchen, and then we crack the lock on Regina's whole dirty history.",
  "Welcome!",
  "Well, I just wanted to let everyone know that we have a new student joining us. She just moved here all the way from Africa.",
  "Well, I mean you wouldn't buy a skirt without asking your friends first if it looks good on you.",
  "Well... I'm kinda psychic. I have a fifth sense.",
  "Well... they can tell when it's raining.",
  "What are \"frenemies\"?",
  "What are marijuana tablets?",
  "What is happening to the world?",
  "What, no one wants large?",
  "Whatever, I'm getting cheese fries.",
  "Whatever. Those rules aren't even real.",
  "Who cares? Six of those girls are right!",
  "Why are you dressed so scary?",
  "Why didn't they just keep home schooling you?",
  "Why do you wear your hair like that? Your hair looks so sexy pushed back. Cady, will you please tell him his hair looks sexy pushed back?",
  "Why don't I know you?",
  "Why should Caesar get to stomp around like a giant, while the rest of us try not to get smushed under his big feet? What's so great about Caesar? Hm? Brutus is just as cute as Caesar. Kay, Brutus is just as smart as Caesar. People totally like Brutus just as much as they like Caesar. And when did it become okay for one person to be the boss of everybody, huh? Because that's not what Rome is about. We should totally just *stab* Caesar!",
  "Would you like us to assign someone to butter your muffin?",
  "Wow, Damian, you've truely out-gayed yourself.",
  "Wow. Your house is really nice.",
  "Yeah! Take your top off!",
  "Yeah, but he's my first cousin.",
  "Yeah, but tonight's the night i like it.",
  "Yeah, he's almost too gay to function.",
  "Yo Yo Yo! All you sucka MCs ain't got nothin' on me! From my grades, to my lines you can't touch Kevin G! I'm a mathlete, so nerd is inferred, but forget what you heard I'm like James Bond the third, sh-sh-sh-shaken not stirred - I'm Kevin Gnapoor! The G's silent when I sneak through your door. And make love to your woman on the bathroom floor. I don't play it like Shaggy, you'll know it was me. Cause the next time you see her she'll be like, OOH! KEVIN G!",
  "You can't join Mathletes, it's social suicide!",
  "You can't sit with us!",
  "You got your freshmen, ROTC guys, preps, J.V. jocks, Asian nerds, cool Asians, varsity jocks, unfriendly black hotties, girls who eat their feelings, girls who don't eat anything, desperate wannabes, burnouts, sexually active band geeks, the greatest people you will ever meet, and the worst. Beware of the plastics.",
  "You know what? You're the one who made me like this so you could use me for your 8th grade revenge!",
  "You Puerto Rican?",
  "You smell like a baby prostitute.",
  "You still an asshole?",
  "You want to do something fun? You want to go to Taco Bell?",
  "Your face smells like peppermint!",
  "Your grandmother and I have that in common.",
  "Your mom's chest hair!",
  "Your parents have been eaten by cannibals!",
  "You're a regulation hottie."
];
